version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      # Log in to Docker Hub
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  build:
    commands:
      
      # Build the Docker image
      docker build -t sanjayvrs/mediafinalred:5 .
  post_build:
    commands:
      # Push the Docker image to Docker Hub
      docker push sanjayvrs/mediafinalred:5
      
      printf '[{"name":"service-ecs-demo-app","imageUri":"sanjayvrs/mediafinalred:5"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
