version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      # Log in to Docker Hub
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      # Generate a unique tag for the Docker image
      TAG="$(echo $CODEBUILD_BUILD_ID | cut -d':' -f2)"
      export IMAGE_TAG="sanjayvrs/mediafinalred:$TAG"

  build:
    commands:
     
      # Build the Docker image with the dynamically generated tag
      docker build -t "$IMAGE_TAG" .
      # Tag the image with the latest tag
      docker tag "$IMAGE_TAG" sanjayvrs/mediafinalred:latest

  post_build:
    commands:
      # Push the Docker image to Docker Hub
      docker push "$IMAGE_TAG"
      docker push sanjayvrs/mediafinalred:latest
      # Create images.json file
      printf '[{"name":"mediafinalred","imageUri":"sanjayvrs/mediafinalred"}]' > images.json

artifacts:
  files:
    - images.json
