AWSTemplateFormatVersion: '2010-09-09'
Description: |
    This AWS CloudFormation template manages secrets using AWS Secrets Manager. 
    It defines parameters for specifying AMI IDs and credentials, and creates 
    Secrets Manager secrets for storing sensitive information securely.
Parameters:
  AMIVParam:
    Type: String
    Description: "AMI for AMI for region n.Virginia"
  AMIOParam:
    Type: String
    Description: "AMI for region Ohio"
  AMINCParam:
    Type: String
    Description: "AMI for region n.California"
  UsernameParam:
    Type: String
    Description: "Username for the Secret"
  PasswordParam:
    Type: String
    Description: "Password for the Secret"

Resources:
  MySecretB:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: RDScreds
      Description: Secret for RDS username and password
      SecretString: !Sub '{"username":"${UsernameParam}","password":"${PasswordParam}"}'
      Tags:
        - Key: Thoughtworks
          Value: RDS
  AMIV:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: AMIV
      Description: "AMI for region north virginia"
      SecretString: !Sub '{"ami": "${AMIVParam}"}'
  AMIO:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: AMIO
      Description: "AMI for region ohio"
      SecretString: !Sub '{"ami": "${AMIOParam}"}'
  AMINC:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: AMINC
      Description: "AMI for region north california"
      SecretString: !Sub '{"ami": "${AMINCParam}"}'

